### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by Jerryeatsbeans** [Nexoria-Studios-CL/Achievment-Friendly-Furniture-Pack#2]
I don't know if you're interested but I made a model for the addon, you can message me on Discord @jerryeatsbeans or email me at jerryeatsbeans@gmail.com if you want to add this

P.S - I'd love to help make models for this!

## Ancient Gem Monument

![image](https://github.com/Nexoria-Studios-CL/Achievment-Friendly-Furniture-Pack/assets/120273220/65ed31b6-7404-45be-9066-bc61a94b1d30) ![image](https://github.com/Nexoria-Studios-CL/Achievment-Friendly-Furniture-Pack/assets/120273220/ea998501-b1b6-4ca8-a5e7-64b30b7a7e06)
![image](https://github.com/Nexoria-Studios-CL/Achievment-Friendly-Furniture-Pack/assets/120273220/a46fad44-ba15-466e-b8f7-33ab7064e601)

**Comment by GuiRafaCL** [comment]
Wow, this is reallyyyy good, I will definitely use it and give credit, thank you very much for the contribution!

**Comment by GuiRafaCL** [comment]
Already sent you a e-mail, thanks again!
